# Site
title: Loogeking's Blog
subtitle: '代码改变世界'
description: '个人技术博客'
keywords: 博客,技术,前端
author: Loogeking
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://loogeking.github.io
permalink: posts/:title/

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''

# Home page setting
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Pagination
per_page: 8

# Extensions
theme: butterfly

# ========== 代码高亮（关闭行号）==========
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''

# Math
math:
  use: mathjax
  per_page: true
  hide_scrollbar: false

mathjax:
  enable: true
  per_page: true

markdown:
  plugins:
    - markdown-it-mathjax3

# 归档页面设置 (Archive)
archive_generator:
  per_page: 0
  yearly: true
  monthly: true

# 分类页面设置 (Category)
category_generator:
  per_page: 0

# 标签页面设置 (Tag)
tag_generator:
  per_page: 0