# Site
title: Loogeking's Blog
subtitle: '代码改变世界'
description: '个人技术博客'
keywords: 博客,技术,前端
author: Loogeking
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://loogeking.github.io
permalink: posts/:title/

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''

# Home page setting
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Pagination
per_page: 8

# Extensions
theme: butterfly